# Generated by Django 6.0.4 on 2026-05-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='shift',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Morning', 'Morning (9 AM - 1 PM)'), ('Evening', 'Evening (2 PM - 6 PM)')], default='Full-time', max_length=20),
        ),
    ]
