# Generated by Django 6.0.4 on 2026-05-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_asset_additional_notes_asset_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='external_storage',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('SSD', 'SSD'), ('HDD', 'HDD'), ('M.2 NVMe', 'M.2 NVMe'), ('External Hub', 'External Hub'), ('Docking Station', 'Docking Station'), ('Other', 'Other')], default='None', max_length=100, null=True),
        ),
    ]
