# Generated by Django 6.0.4 on 2026-05-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_asset_external_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='cpu',
            field=models.CharField(choices=[('Intel Core i5', 'Intel Core i5'), ('Intel Core i7', 'Intel Core i7'), ('Intel Core i9', 'Intel Core i9'), ('Apple M1', 'Apple M1'), ('Apple M2', 'Apple M2'), ('Apple M3', 'Apple M3'), ('AMD Ryzen 5', 'AMD Ryzen 5'), ('AMD Ryzen 7', 'AMD Ryzen 7'), ('Other', 'Other')], default='Intel Core i7', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='external_storage_size',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('256GB', '256GB'), ('512GB', '512GB'), ('1TB', '1TB'), ('2TB', '2TB'), ('Other', 'Other')], default='N/A', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='os',
            field=models.CharField(choices=[('Windows 11 Pro', 'Windows 11 Pro'), ('Windows 10 Pro', 'Windows 10 Pro'), ('macOS Sonoma', 'macOS Sonoma'), ('macOS Ventura', 'macOS Ventura'), ('Ubuntu 22.04', 'Ubuntu 22.04'), ('Other', 'Other')], default='Windows 11 Pro', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='ram',
            field=models.CharField(choices=[('8GB', '8GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('Other', 'Other')], default='16GB', max_length=50),
        ),
    ]
